### ISSUE TITLE
POI Daten laden -Own POIs Resultlistpage

### ISSUE THREAD

**Issue by alpenkind** [coding-bootcamps-eu/final-project-2024-01-accessibility#95]
POI Daten aus Datenbank laden die durch Account erstellt wurden

**Comment by EricRump** [comment]
Daten verbinden mit user id mit einer v-if, damit nur eigene pois angezeigt werden ( aktuell werden alle angezeigt

**Comment by EricRump** [comment]
und symbole und entfernung müssen noch auf die buttons
